device: "0,1,2,3"
data_path: "./image/diff1107"
model_save_path: "./result/model_Vit_base_warnup2"

### DDP setting
use_ddp: True
port: 8994

### training setting

# continue training
load_state: False
load_model_path: 
skip_epoch: 10

# data
spilt_rate: 0.8

# data loader
batch_size: 32
num_workers: 6

# lr
lr: 0.001

# scheduler
lrf: 0.2
momentum: 0.937
weight_decay: 0.00005
warmup: False
warmup_step: 3

# other
epoch: 1000
accumulation_step: 2
cosanneal_cycle: 50
save_frequency: 2

### Model 

# Vit Base
patch_size: 16
img_size: 224
emb_size: 768
depth: 12
num_heads: 12

# Vit Large
# patch_size: 16
# img_size: 224
# emb_size: 1024
# depth: 24
# num_heads: 16

drop_p: 0

expansion: 4

in_channels: 3
n_classes: 142
