device: "0,1,2,3,4,5,6,7"

seed: 8603

# for train data
data_path: "./image/all_word" # "./image/diff1107" 
# for eval data
val_data_path: # "./image/rare1107"

model_save_path: "./result/all15000/Vit_large_pos_warmup3_raAttn/"

### DDP setting
use_ddp: True
port: 8888 # 8994

### training setting

# eval
load_model_path: "result/all15000/Vit_large_pos_warmup3/model_40_0.998_.pth"

# continue training
load_state: False
skip_epoch: 10

# data
spilt_rate: 0.8

# data loader
batch_size: 64
num_workers: 6

# lr
lr: 0.001

# scheduler
lrf: 0.0005
momentum: 0.937
weight_decay: 0.00005
warmup: True
warmup_step: 3
warmup_start_value: 0.0001

# other
epoch: 500
accumulation_step: 8
cosanneal_cycle: 50 # 30
save_frequency: 2
reAttention: True

### Model 

# Vit Base
# patch_size: 16
# img_size: 224
# emb_size: 768
# depth: 12
# num_heads: 12

# Vit Large
patch_size: 16
img_size: 224
emb_size: 1024
depth: 24
num_heads: 16

decoder_embed_dim: 768
decoder_depth: 8
decoder_heads: 16

drop_p: 0

expansion: 4

in_channels: 3
n_classes: 142
