device: "0"
data_path: "./image/diff1107"
model_save_path: "./result/model"
spilt_rate: 0.8

batch_size: 48
num_workers: 6
lr: 0.001
lrf: 0.2
momentum: 0.937
weight_decay: 0.00005
epoch: 1000
accumulation_step: 4

# Vit Base
patch_size: 16
img_size: 224
emb_size: 768
depth: 12
num_heads: 12

# Vit Large
# patch_size: 16
# img_size: 224
# emb_size: 1024
# depth: 24
# num_heads: 16

drop_p: 0

expansion: 4


in_channels: 3
n_classes: 142
