device: "0"
data_path: "./image/diff1107"
model_save_path: "./result/model"
spilt_rate: 0.8

batch_size: 32
num_workers: 6
lrf: 0.2
momentum: 0.937
weight_decay: 0.00005
epoch: 1000


patch_size: 16
img_size: 224
emb_size: 768
att_emb: 768
drop_p: 0
depth: 12
expansion: 4
num_heads: 8

in_channels: 3
n_classes: 1000
