device: "4,5,6,7"

# for train data
data_path: "./image/diff1107"
# for eval data
val_data_path: "./image/rare1107"

model_save_path: "./result/Vit_large_pos_warmup3"

### DDP setting
use_ddp: True
port: 8888 # 8994

### training setting

# eval
load_model_path: "./result/vit_base_warmup3_non_pos/model_32_0.993_.pth"

# continue training
load_state: False
skip_epoch: 10

# data
spilt_rate: 0.8

# data loader
batch_size: 32
num_workers: 6

# lr
lr: 0.001

# scheduler
lrf: 0.2
momentum: 0.937
weight_decay: 0.00005
warmup: True
warmup_step: 3

# other
epoch: 50
accumulation_step: 2
cosanneal_cycle: 50
save_frequency: 2

### Model 

# Vit Base
# patch_size: 16
# img_size: 224
# emb_size: 768
# depth: 12
# num_heads: 12

# Vit Large
patch_size: 16
img_size: 224
emb_size: 1024
depth: 24
num_heads: 16

decoder_embed_dim: 768
decoder_depth: 8
decoder_heads: 16

drop_p: 0

expansion: 4

in_channels: 3
n_classes: 142
